INSERT INTO EMPLOYEE (id, name) VALUES (1, 'Sami');
INSERT INTO EMPLOYEE (id, name) VALUES (2, 'Carole1');
INSERT INTO EMPLOYEE (id, name) VALUES (3, 'Carole2');
INSERT INTO EMPLOYEE (id, name) VALUES (4, 'Carole3');
INSERT INTO EMPLOYEE (id, name) VALUES (5, 'Carole4');
INSERT INTO EMPLOYEE (id, name) VALUES (6, 'Carole5');
INSERT INTO EMPLOYEE (id, name) VALUES (7, 'Carole6');
INSERT INTO EMPLOYEE (id, name) VALUES (8, 'Carole7');
INSERT INTO EMPLOYEE (id, name) VALUES (9, 'Carole8');

INSERT INTO BILL (id, name, total, netpayment) VALUES (1, 'bill1', 20.5, 0.0);
INSERT INTO BILL (id, name, total, netpayment) VALUES (2, 'bill2', 30.5, 0.0);
INSERT INTO BILL (id, name, total, netpayment) VALUES (3, 'bill3', 40.5, 0.0);
INSERT INTO BILL (id, name, total, netpayment) VALUES (4, 'bill4', 50.5, 0.0);
INSERT INTO BILL (id, name, total, netpayment) VALUES (5, 'bill5', 60.5, 0.0);
INSERT INTO BILL (id, name, total, netpayment) VALUES (6, 'bill6', 70.5, 0.0);
INSERT INTO BILL (id, name, total, netpayment) VALUES (7, 'bill7', 80.5, 0.0);
INSERT INTO BILL (id, name, total, netpayment) VALUES (8, 'bill8', 90.5, 0.0);
INSERT INTO BILL (id, name, total, netpayment) VALUES (9, 'bill9', 100.5, 0.0);
INSERT INTO BILL (id, name, total, netpayment) VALUES (10, 'bill10', 110.5, 0.0);